FROM tensorflow/serving:2.11.1-gpu AS build

ENV MODEL_BASE_PATH /models
ENV MODEL_NAME brain_tumor_detection

RUN mkdir -p /usr/src/models
COPY ./brain_tumor_detection/ /usr/src/models/brain_tumor_detection
COPY ./brain_tumor_detection/ /models/brain_tumor_detection
